name = "WhereTheWaterFlows"
uuid = "ea906314-1493-4d22-a0af-f886a20c9fba"
authors = ["Mauro Werder <mauro3@runbox.com>"]
version = "0.10.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[extensions]
PyPlotExt = "PyPlot"

[compat]
OffsetArrays = "1"
PyPlot = "2"
StaticArrays = "0.11.1, 0.12, 1.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
