name = "WhereTheWaterFlows"
uuid = "ea906314-1493-4d22-a0af-f886a20c9fba"
authors = ["Mauro Werder <mauro3@runbox.com>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Requires = "0.5.2"
StaticArrays = "0.12"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
